# Generated by Django 3.2.7 on 2021-09-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawncatalog', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(default=1, help_text='What type of item is this?', on_delete=django.db.models.deletion.RESTRICT, to='pawncatalog.itemtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='What is this item called?', max_length=200),
        ),
    ]
