# Generated by Django 3.2.7 on 2021-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawncatalog', '0003_auto_20210903_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
