# Generated by Django 3.2.7 on 2021-09-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawncatalog', '0004_auto_20210903_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
