# Generated by Django 3.2.7 on 2021-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawncatalog', '0005_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
