# Generated by Django 3.2.7 on 2021-09-09 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unknown', max_length=100)),
                ('last_name', models.CharField(default='Unknown', max_length=100)),
                ('country', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What is this item called?', max_length=200)),
                ('condition', models.CharField(blank=True, choices=[('n', 'New'), ('g', 'Gently used'), ('u', 'Used'), ('v', 'Very used')], default='n', help_text='In what condition is this item?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What kind of item type?', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What kind of transaction is it?', max_length=100)),
                ('in_store', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='When did this transaction occur?')),
                ('authorizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pawncatalog.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawncatalog.item')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pawncatalog.transactiontype')),
            ],
            options={
                'ordering': ['-date'],
                'permissions': (('can_authorize', 'Can authorize a transaction'),),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(help_text='What type of item is this?', on_delete=django.db.models.deletion.RESTRICT, to='pawncatalog.itemtype'),
        ),
    ]
