# Generated by Django 3.2.7 on 2021-09-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What is this customer's name?", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What item is this?', max_length=200)),
                ('condition', models.CharField(blank=True, choices=[('n', 'New'), ('g', 'Gently used'), ('u', 'Used'), ('v', 'Very used')], default='n', help_text='In what condition is this item?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What kind of item type?', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What kind of transaction is it?', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='When did this transaction occur?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pawncatalog.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawncatalog.item')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pawncatalog.transactiontype')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
