# Generated by Django 3.2.7 on 2021-09-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawncatalog', '0007_transaction_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='borrower',
            new_name='authorizer',
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='in_store',
            field=models.BooleanField(default=True),
        ),
    ]
