# Generated by Django 3.2.7 on 2021-09-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawncatalog', '0008_auto_20210906_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'permissions': (('can_authorize', 'Can authorize a transaction'),)},
        ),
    ]
